### ISSUE TITLE
Update Incubator docs

### ISSUE THREAD

**Issue by mortenhaahr** [INTO-CPS-Association/DTaaS-examples#38]
From #28: Update the README with explanation of the results seen in Influx dashboards. If there is a way to upload the Influx dashboard config (like done in firefighter example), that would be great. Add a couple of useful screenshots from InfluxDB dashboards.

**Comment by prasadtalasila** [comment]
Only the upload of influx dashboard config is pending.

**Comment by mortenhaahr** [comment]
Turns out that I had made a mistake.
The InfluxDB dashboard is automatically imported when the Incubator is executed.

I made a PR that updates this in the README

**Comment by mortenhaahr** [comment]
After a discussion with Prasad:
The dashboard is not automatically important when executed on DTaaS.
This only happens when the original Docker version of the Incubator is used.
Reopening.
